void copyconfig (config& c, config& d);
int replace (config* cc, int k, config c0, int pos, bool p, int s);
void fronttrim (config* cc, int i, config* cc0, int j);
void endtrim (config* cc, int i, config* cc0, int j);
int comefrom (config* cc, machine &m, config c);
int smartcomefrom (config* cc, machine m, config c);
void reduce (config* cc, int k, int len);
bool eql (config c1, config c2);
int boom (config* cc, machine m, config* cc0, int len);
int multicomefrom (config* cc, machine m, config c, int l, int room);
int allcomefrom (config* ff, machine m, config c, int l, int room);
